<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- 定义 base_link 宏 -->
    <xacro:macro name="base_xacro" params="length:=0.1 radius:=0.05">
        <link name="base_footprint" />

        <link name="base_link">
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${radius}" length="${length}"/>
                </geometry>
                <material name="white"> 
                    <color rgba="1.0 1.0 1.0 0.5"/>
                </material>
            </visual>
        </link> 

        <joint name="base_footprint_to_base_link" type="fixed">
            <parent link="base_footprint"/>
            <child link="base_link"/>
            <origin xyz="0.0 0.0 ${length/2+0.032-0.001}" rpy="0.0 0.0 0.0"/>
        </joint>
    </xacro:macro> 

</robot>